### ISSUE TITLE
Cannot catch EADDRINUSE

### ISSUE THREAD

**Issue by c7hm4r** [libp2p/js-libp2p-websockets#184]
Hello! I want to implement that a different port is tried automatically when the currently tried out port is in use. However, it is impossible to catch the EADDRINUSE exception when running `await node.start();`. NodeJS terminates before `node.start()` returns a Promise.

Following is output:
```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8000
    at Server.setupListenHandle [as _listen2] (node:net:1485:16)
    at listenInCluster (node:net:1533:12)
    at Server.listen (node:net:1621:7)
    at file:///project/node_modules/it-ws/dist/src/server.js:14:25
    at new Promise (<anonymous>)
    at Server.listen (file:///project/node_modules/it-ws/dist/src/server.js:12:22)
    at WebSocketListener.listen (file:///project/node_modules/@libp2p/websockets/dist/src/listener.js:72:27)
    at DefaultTransportManager.listen (file:///project/node_modules/libp2p/dist/src/transport-manager.js:155:37)
    at DefaultTransportManager.start (file:///project/node_modules/libp2p/dist/src/transport-manager.js:44:20)
    at file:///project/node_modules/@libp2p/components/dist/src/index.js:67:29
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (node:events:513:28)
    at emitErrorNT (node:net:1512:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 8000
}

Node.js v18.9.0
```

To me, the issue has a medium severity, because the workaround to check the port usage before is tedious, platform dependent, and cannot be reliable because it is not atomic.

Versions:

- Node.js: 18.9.0
- libp2p: 0.39.1
- @libp2p/websockets: 3.0.3

Possibly related:

- #77

**Comment by achingbrain** [comment]
You could use `0` for the port number, then read the relevant addr from [getMultiaddrs](https://github.com/libp2p/js-libp2p/blob/master/src/index.ts#L151) on the node after startup?

Might be a nicer approach than trying (potentially) lots of new sockets until you find a free one?

**Comment by c7hm4r** [comment]
Thank you. It would be a partial solution for my problem at hand. But in general, it would be nice to be able to at least print a human-friendly error message instead of confronting the user with some technical stack trace.

**Comment by achingbrain** [comment]
I think this should be validated - if a port is in used the error should be catchable, it should not take the process down.

From the error message the `WebSocketServer` needs a handler listening for the `error` event.

**Comment by mpetrunic** [comment]
https://github.com/alanshaw/it-ws/pull/34 should fix this but it's not working for some reason
