### ISSUE TITLE
Crashes when data is not a buffer

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-libp2p-websockets#68]
```
/app/node_modules/pull-reader/state.js:18
        throw new Error('data must be a buffer, was: ' + JSON.stringify(data))
        ^

Error: data must be a buffer, was: ""
    at Object.add (/app/node_modules/pull-reader/state.js:18:15)
    at /app/node_modules/pull-reader/index.js:61:15
    at /app/node_modules/pull-reader/index.js:20:7
    at WebSocket.<anonymous> (/app/node_modules/pull-ws/source.js:31:14)
    at WebSocket.onMessage (/app/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at Receiver.ontext (/app/node_modules/ws/lib/WebSocket.js:841:10)
    at /app/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/app/node_modules/ws/lib/Receiver.js:371:5)
```
Steps to reproduce:
```
npm install -g wscat
wscat -c host:port
# press return after connection
```

Instead the server should call `Buffer.from(data)` on strings or just ignore the data instead of crashing the whole node

**Comment by mpetrunic** [comment]
Don't think this is relevant anymore
